/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  3.3 CP3
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C_SDA_aliases.h"
#include "I2C_SDA.h"
#include "I2C_SCL_aliases.h"
#include "I2C_SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "SPIM.h"
#include "SPIM_PVT.h"
#include "DEBUG_UART.h"
#include "SPIM_MOSI_aliases.h"
#include "SPIM_MOSI.h"
#include "SPIM_SCLK_aliases.h"
#include "SPIM_SCLK.h"
#include "SPIM_SS_aliases.h"
#include "SPIM_SS.h"
#include "SPIM_MISO_aliases.h"
#include "SPIM_MISO.h"
#include "SPIM_IntClock.h"
#include "DEBUG_UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

